### PR TITLE
fix: Authorize /activities endpoint

### LINKED ISSUE #392: Add authorization to the /activities endpoint
The /activities endpoint was mistakenly left 'unauthorized' with issue #388.

### PR DESCRIPTION
**Pull request by bstasyszyn**
No authentication is required for activities sent to "https://www.w3.org/ns/activitystreams#Public".

closes #392

Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>

### CODE REVIEW

**Review by sandrask — APPROVED** [review]

**Review by fqutishat — APPROVED** [review]

File: pkg/activitypub/resthandler/activityhandler.go [hunk 1]
```diff
@@ -292,23 +301,31 @@ func (h *Activity) handle(w http.ResponseWriter, req *http.Request) {
...
 
-		h.writeResponse(w, http.StatusInternalServerError, nil)
+		h.writeResponse(w, http.StatusInternalServerError, []byte("Internal Server Error.\n"))
 
 		return
 	}
 
+	if !authorized {
+		if !activity.To().Contains(vocab.PublicIRI) {
+			h.writeResponse(w, http.StatusUnauthorized, []byte("Unauthorised.\n"))
```
Comment (DRK3) [inline pkg/activitypub/resthandler/activityhandler.go:318]: Better to use consistent spelling on "unauthorized" - (you have a `s` here)

**Review by DRK3 — APPROVED** [review]

File: pkg/activitypub/resthandler/activityhandler.go (hunk 1 above)
Comment (bstasyszyn) [reply pkg/activitypub/resthandler/activityhandler.go:318]: I have another PR coming. I'll change it then.
