### PR TITLE
fix: Race condition in AMQP pooled subscriber

### LINKED ISSUE #542: Race condition in AMQP pooled subscriber close

### PR DESCRIPTION
**Pull request by bstasyszyn**
Fixes a race condition that occasionally occurs in the pooled subscriber stop function.

closes #542

Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>

### CODE REVIEW

File: pkg/pubsub/amqp/pooledsubscriber.go [hunk 1]
```diff
@@ -75,17 +81,46 @@ func newPoolSubscriber(ctx context.Context, n uint, topic string, s subscriber,
 		topic:       topic,
 		msgChan:     msgChan,
 		poolMsgChan: poolMsgChan,
+		stopChan:    make(chan struct{}, 1),
```
Comment (soluchok) [inline pkg/pubsub/amqp/pooledsubscriber.go:84]: You do not need to use the buffered channel.
Changes you need to make:
1. `make(chan struct{}, 1)` - > `make(chan struct{})`
2. `s.stopChan <- struct{}{} ` - > `close(s.stopChan)`

**Review by sandrask — APPROVED** [review]

File: pkg/pubsub/amqp/pooledsubscriber.go (hunk 1 above)
Comment (bstasyszyn) [reply pkg/pubsub/amqp/pooledsubscriber.go:84]: I need a buffer since the listener may already have been stopped by msgChan closing (this happens if the AMQP connection closes). In this case there will be no listener on the stopChan and then s.stopChan <- struct{}{} would hang.

**Review by soluchok — APPROVED** [review]
