### PR TITLE
fix: Process anchor event immediately if witness policy does not require witnesses

### LINKED ISSUE #1064: Process anchor event without witnesses if policy doesn't require witnesses
If the witness policy states that no proofs are required from external witnesses then the anchor event should be processed with only the proof of the local server. Currently if no witnesses are configured then the anchor event fails to be processed. This is useful for running a standalone server in a development environment.

### PR DESCRIPTION
**Pull request by bstasyszyn**
For a standalone domain, where no witnesses are configured and the witness policy states that I don't need witnesses, the anchor event is processed immediately using only the proof of the local domain.

closes #1064

Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>

### CODE REVIEW

**Review by fqutishat — APPROVED** [review]

File: pkg/anchor/writer/writer.go [hunk 1]
```diff
@@ -611,10 +617,29 @@ func (c *Writer) postOfferActivity(anchorEvent *vocab.AnchorEventType, batchWitn
...
 	}
 
-	logger.Debugf("created pre-announce activity for anchor event[%s], post id[%s]", anchorEvent.Index(), postID)
+	logger.Debugf("created pre-announce activity for anchor index[%s], post id[%s]", anchorEvent.Index(), postID)
+
+	if len(witnessesIRI) == 1 {
+		// The Offer was posted only to the public IRI. This means that it will be persisted
+		// in the ActivityPub Outbox (to be viewed by anyone) but won't be sent to any service.
+		// In this case we can handle the anchor event immediately.
+		logger.Debugf("According to witness policy, no witnesses are required for anchor index[%s]. "+
```
Comment (troyronda) [inline pkg/anchor/writer/writer.go:629]: Is this is due to *both* the witness policy and having no witnesses in the witness collection?

If there is a witness in the witness collection, we should still try to send the Offer. I assume this is still the case in this PR.

**Review by troyronda — APPROVED** [review]

File: pkg/anchor/writer/writer.go (hunk 1 above)
Comment (bstasyszyn) [reply pkg/anchor/writer/writer.go:629]: No, if the witness policy says no witnesses required then an offer is not sent. I don't know what to do in this case, i.e. what if we have 20 witnesses - do we send to all? Currently we determine (based on policy) the minimal set of witnesses to which to send. Also, if we still send the offer to witnesses, how do we know when to anchor the batch? Currently we anchor immediately after satisfying the policy.

If someone configured their policy to not require witnesses, doesn't that mean they don't want the anchors to be witnessed?
