### PR TITLE
fix: Panic in iterator when no references found in an activity query

### LINKED ISSUE #310: Panic in ariesstore/activityIterator.Close
orb.domain1.com          |  [activitypub_store] 2021/04/27 23:09:10 UTC - ariesstore.(*Provider).QueryReferences -> DEBUG [/services/orb] Querying references of type LIKED - Query: &{Types:[] ReferenceType:LIKED ObjectIRI:https://orb.domain1.com/services/orb ReferenceIRI:<nil> ActivityIRIs:[]}
orb.domain1.com          | 2021/04/27 23:09:10 http: panic serving 172.26.0.1:58004: runtime error: invalid memory address or nil pointer dereference
orb.domain1.com          | goroutine 788 [running]:
orb.domain1.com          | net/http.(*conn).serve.func1(0xc000298500)
orb.domain1.com          | 	/usr/local/go/src/net/http/server.go:1824 +0x153
orb.domain1.com          | panic(0xe3bec0, 0x1766b20)
orb.domain1.com          | 	/usr/local/go/src/runtime/panic.go:971 +0x499
orb.domain1.com          | github.com/trustbloc/orb/pkg/activitypub/store/ariesstore.(*activityIterator).Close(0xc0000aee90, 0x1, 0x0)
orb.domain1.com          | 	/go/src/github.com/trustbloc/orb/pkg/activitypub/store/ariesstore/ariesstore.go:354 +0x29
orb.domain1.com          | github.com/trustbloc/orb/pkg/activitypub/resthandler.(*Activities).getPage.func1(0x11e1690, 0xc0000aee90, 0xc0004157c8)
orb.domain1.com          | 	/go/src/github.com/trustbloc/orb/pkg/activitypub/resthandler/activityhandler.go:225 +0x35
orb.domain1.com          | panic(0xe3bec0, 0x1766b20)
orb.domain1.com          | 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
orb.domain1.com          | github.com/trustbloc/orb/pkg/activitypub/store/ariesstore.(*activityIterator).Next(0xc0000aee90, 0xc00005ec00, 0x0, 0xc0004156b0)
orb.domain1.com          | 	/go/src/github.com/trustbloc/orb/pkg/activitypub/store/ariesstore/ariesstore.go:329 +0x2d
orb.domain1.com          | github.com/trustbloc/orb/pkg/activitypub/store/storeutil.ReadActivities(0x11e1690, 0xc0000aee90, 0x64, 0xc000154870, 0x2, 0x11e1690, 0xc0000aee90, 0x0)
orb.domain1.com          | 	/go/src/github.com/trustbloc/orb/pkg/activitypub/store/storeutil/storeutil.go:58 +0x9a
orb.domain1.com          | github.com/trustbloc/orb/pkg/activitypub/resthandler.(*Activities).getPage(0xc000337830, 0xc00015c870, 0xc0003859e0, 0xc0003d7eb0, 0x2, 0x2, 0x0, 0x0, 0x0)
orb.domain1.com          | 	/go/src/github.com/trustbloc/orb/pkg/activitypub/resthandler/activityhandler.go:233 +0x216
orb.domain1.com          | github.com/trustbloc/orb/pkg/activitypub/resthandler.(*Activities).handleActivitiesPage(0xc000337830, 0x11e1d80, 0xc0002de000, 0xc0004e0900, 0xc00015c870, 0xc0003859e0)
orb.domain1.com          | 	/go/src/github.com/trustbloc/orb/pkg/activitypub/resthandler/activityhandler.go:148 +0x62c
orb.domain1.com          | github.com/trustbloc/orb/pkg/activitypub/resthandler.(*Activities).handle(0xc000337830, 0x11e1d80, 0xc0002de000, 0xc0004e0900)
orb.domain1.com          | 	/go/src/github.com/trustbloc/orb/pkg/activitypub/resthandler/activityhandler.go:105 +0x50d

### PR DESCRIPTION
**Pull request by DRK3**
closes #310

Signed-off-by: Derek Trider <Derek.Trider@securekey.com>

### CODE REVIEW

**Review by bstasyszyn — APPROVED** [review]

File: pkg/activitypub/store/ariesstore/ariesstore.go [hunk 1]
```diff
@@ -284,7 +284,7 @@ func (s *Provider) queryActivitiesByRef(refType spi.ReferenceType, query *spi.Cr
 	}
 
 	if len(refs) == 0 {
-		return &activityIterator{}, nil
+		return memstore.NewActivityIterator(nil, 0), nil
```
Comment (bstasyszyn) [inline pkg/activitypub/store/ariesstore/ariesstore.go:287]: It's a bit weird to use an iterator from another implementation. It may be better to just add a check for nil ariesIterator in each of the functions. Maybe something to look at in the future PR.

**Review by bstasyszyn — APPROVED** [review]

**Review by sandrask — APPROVED** [review]

File: pkg/activitypub/store/ariesstore/ariesstore.go (hunk 1 above)
Comment (DRK3) [reply pkg/activitypub/store/ariesstore/ariesstore.go:287]: Makes sense. Eventually I should be consolidating the two storage implementations, so it would make sense to do it then.

Comment (DRK3) [reply pkg/activitypub/store/ariesstore/ariesstore.go:287]: ^^ Just realized that last comment may have been a bit odd-sounding: By that I mean: I see what you're saying. I'll definitely do that in a future PR

Comment (DRK3) [reply pkg/activitypub/store/ariesstore/ariesstore.go:287]: I also use the mem iterator in another function (although I actually pass in stuff to the struct)
